[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aocd = "0.4.0"
image = "0.25.5"
itertools = "0.13.0"
nalgebra = "0.33.2"
rayon = "1.10.0"
regex = "1.10.2"
