[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aocd = "0.4.0"
itertools = "0.12.0"
nalgebra = "0.32.3"
num = "0.4.1"
onig = "6.4.0"
regex = "1.10.2"
z3 = "0.12.1"
